Repository uber/causalml, pull requests merged in 2019-09, with the labels that each got.

#45 update plots in metrics. add qini_score to metrics
  causalml/metrics/__init__.py
  causalml/metrics/visualize.py
Labels: enhancement

#46 Use the correct import path for S/T/X/R Leaners
  README.md
Labels: documentation

#53 Update changelog.rst for 0.3.0 release
  docs/changelog.rst
Labels: documentation

#57 fix index error in XGBRRegressor with early_stopping=True
  causalml/inference/meta/rlearner.py
Labels: bug
