Repository uber/causalml, pull requests merged in 2019-08, with the labels that each got.

#23 add .readthedocs.yml. rename docs/requirements-docs.txt
  .readthedocs.yml
  Makefile
  README.md
  causalml/__init__.py
  docs/changelog.rst
  docs/conf.py
  docs/requirements.txt
  setup.py
Labels: documentation

#24 add matplotlib to docs/requirements.txt for docs/conf.py
  docs/requirements.txt
Labels: documentation

#27 Fix LINUX installation error
  .readthedocs.yml
  .travis.yml
  MANIFEST.in
  causalml/__init__.py
  requirements-test.txt
  requirements.txt
  setup.py
Labels: bug

#28 add causalml *.pyx, *.pxd, *.c, *.h to MANIFAST.in
  MANIFEST.in
  causalml/__init__.py
  setup.py
Labels: bug

#31 Move meta classifiers
  causalml/inference/meta/__init__.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/xlearner.py
  tests/conftest.py
  tests/const.py
  tests/test_meta_learners.py
  tests/test_metrics.py
  tests/test_uplift_trees.py
Labels: enhancement

#35 Fix uplift curves
  README.md
  causalml/__init__.py
  causalml/inference/meta/xlearner.py
  causalml/metrics/__init__.py
  causalml/metrics/synthetic.py
  causalml/metrics/visualize.py
  docs/changelog.rst
  docs/examples.rst
  examples/meta_learners_with_synthetic_data.ipynb
  setup.py
  tests/conftest.py
  tests/test_meta_learners.py
  tests/test_uplift_trees.py
Labels: bug

#43 Log metrics for meta-learners
  causalml/__init__.py
  causalml/dataset/__init__.py
  causalml/dataset/synthetic.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/xlearner.py
  causalml/metrics/__init__.py
  causalml/metrics/classification.py
  causalml/metrics/regression.py
  causalml/metrics/visualize.py
  examples/meta_learners_with_synthetic_data.ipynb
  examples/meta_learners_with_synthetic_data_multiple_treatment.ipynb
  tests/test_datasets.py
  tests/test_meta_learners.py
  tests/test_uplift_trees.py
Labels: enhancement

#44 Hotfix for a bug in S-Learner: treatment was flipped
  causalml/inference/meta/slearner.py
Labels: bug

#42 add xgboost ranking algo for rlearner regressor
  causalml/inference/meta/__init__.py
  causalml/inference/meta/rlearner.py
  causalml/metrics/visualize.py
Labels: enhancement
