Repository uber/causalml, pull requests merged in 2019-10, with the labels that each got.

#64 Add the link to API doc to README.md
  README.md
Labels: documentation

#66 bug fix for BaseRClassifier.fit() with multiple treatments
  causalml/inference/meta/rlearner.py
Labels: bug

#63 uplift tree visualization
  causalml/inference/tree/__init__.py
  causalml/inference/tree/models.py
  causalml/inference/tree/plot.py
  causalml/inference/tree/utils.py
  examples/uplift_tree_visualization.ipynb
  requirements.txt
Labels: enhancement

#58 Add feature_importance functionality for base meta learners
  causalml/inference/meta/explainer.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/utils.py
  causalml/inference/meta/xlearner.py
  examples/feature_interpretations_example.ipynb
  requirements.txt
Labels: enhancement

#68 Update Quickstart guide with missing import and array indexing
  README.md
Labels: documentation

#69 add bootstrap confidence intervals; updated the example notebook with bootstrap CI for ATE
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/xlearner.py
  examples/meta_learners_with_synthetic_data_multiple_treatment.ipynb
  requirements.txt
Labels: enhancement

#72 More feature explanation updates
  causalml/inference/meta/explainer.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/xlearner.py
  examples/feature_interpretations_example.ipynb
Labels: enhancement

#74 0.4.0 release documentation
  README.md
  causalml/__init__.py
  docs/_static/img/shap_vis.png
  docs/_static/img/uplift_tree_vis.png
  docs/changelog.rst
  docs/examples.rst
  docs/index.rst
  docs/interpretation.rst
  docs/methodology.rst
Labels: documentation

#75 fix the version discrepency by using causalml.__version__ in setup.py
  setup.py
Labels: documentation
