Repository uber/causalml, pull requests merged in 2019-11, with the labels that each got.

#78 Specify setup_requires in setup.py
  setup.py
Labels: installation

#79 Uplift tree plot contains edges connecting to wrong parent node
  causalml/inference/tree/plot.py
Labels: bug

#80 Add Targeted Maximum Likelihood Estimation
  causalml/__init__.py
  causalml/inference/meta/__init__.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tmle.py
  causalml/inference/meta/xlearner.py
  causalml/propensity.py
  examples/validation_with_tmle.ipynb
  requirements.txt
  setup.py
Labels: enhancement

#84 Drop Python 2 support. Bump up the version to 0.5.0
  causalml/__init__.py
  causalml/dataset/regression.py
  causalml/inference/tree/causaltree.pyx
  docs/changelog.rst
  docs/requirements.txt
  requirements.txt
  setup.py
Labels: dependencies

#85 Add proportion of sample in addition to total sample size (#73)
  causalml/inference/tree/plot.py
Labels: enhancement

#87 Enhance tree plot with node colors indicating positive and negative uplifts (#86)
  causalml/inference/tree/plot.py
Labels: enhancement

#90 Update DGP for regression with an option for imbalanced propensity
  causalml/dataset/regression.py
Labels: enhancement

#91 Update changelogs for 0.5.0 release
  docs/changelog.rst
Labels: documentation
