Repository uber/causalml, pull requests merged in 2019-12, with the labels that each got.

#93 Add docs badge to readme
  README.md
Labels: documentation

#99 big batch of typo fixes
  causalml/dataset/classification.py
  causalml/dataset/regression.py
  causalml/dataset/synthetic.py
  causalml/features.py
  causalml/inference/meta/explainer.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/xlearner.py
  causalml/inference/tree/causaltree.pyx
  causalml/inference/tree/models.py
  causalml/inference/tree/plot.py
  causalml/match.py
  causalml/metrics/classification.py
  causalml/metrics/regression.py
  causalml/optimize/policylearner.py
  docs/changelog.rst
  docs/examples.rst
  docs/validation.rst
  tests/test_uplift_trees.py
Labels: documentation

#105 Fix impurity computation
  causalml/inference/tree/causaltree.pyx
Labels: bug

#103 add cython instructions to contributor docs
  CONTRIBUTING.md
Labels: documentation

#102 Xgboost objective names
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/utils.py
  requirements.txt
Labels: warning

#97 accept pandas inputs for meta learners + add tests
  causalml/dataset/synthetic.py
  causalml/inference/meta/explainer.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/tmle.py
  causalml/inference/meta/utils.py
  causalml/inference/meta/xlearner.py
  tests/test_datasets.py
  tests/test_meta_learners.py
Labels: enhancement

#110 Add sanity checks for propensity score values
  causalml/inference/meta/utils.py
Labels: enhancement

#112 Fix ImportError
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/tmle.py
  causalml/inference/meta/xlearner.py
  requirements-test.txt
  requirements.txt
Labels: bug

#108 Speed up UpliftTreeClassifier
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/tmle.py
  causalml/inference/meta/xlearner.py
  causalml/inference/tree/models.py
  causalml/inference/tree/plot.py
  causalml/inference/tree/utils.py
  causalml/match.py
  causalml/metrics/classification.py
  causalml/metrics/regression.py
  causalml/metrics/visualize.py
  causalml/optimize/policylearner.py
  causalml/propensity.py
  examples/uplift_tree_visualization.ipynb
  examples/uplift_trees_with_synthetic_data.ipynb
  tests/test_uplift_trees.py
Labels: enhancement
