Repository uber/causalml, pull requests merged in 2020-11, with the labels that each got.

#256 Refactoring the Code by using String Format Arguments, removing Unnecessary Comprehensions and using `is` to compare Object Types
  causalml/inference/meta/explainer.py
  causalml/inference/meta/utils.py
  causalml/inference/tree/plot.py
  causalml/inference/tree/utils.py
  causalml/match.py
  causalml/metrics/sensitivity.py
Labels: refactoring

#258 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#259 adding the contributors section to README.md
  README.md
Labels: documentation

#260 Changing methods not using its bound instance to staticmethods
  causalml/feature_selection/filters.py
  causalml/inference/tree/models.py
  causalml/metrics/sensitivity.py
  causalml/optimize/unit_selection.py
Labels: refactoring

#262 Pass in the optional n_fold and random_state arguments to StratifiedK…
  causalml/propensity.py
Labels: bug
