Repository uber/causalml, pull requests merged in 2020-01, with the labels that each got.

#116 0.6.0 release
  causalml/__init__.py
  docs/changelog.rst
  docs/requirements.txt
  setup.py
Labels: documentation

#115 Causaltree refactor
  causalml/inference/tree/causaltree.pyx
  requirements.txt
Labels: enhancement

#123 Replace ELI5 permutation importance with sklearn's
  causalml/inference/meta/explainer.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/xlearner.py
  examples/feature_interpretations_example.ipynb
  requirements.txt
Labels: enhancement

#113 make propensity score optional in X and R Learner
  causalml/dataset/synthetic.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/xlearner.py
  causalml/propensity.py
  examples/meta_learners_with_synthetic_data.ipynb
  examples/meta_learners_with_synthetic_data_multiple_treatment.ipynb
  tests/test_meta_learners.py
Labels: enhancement

#125 Specify explicit column indexing
  causalml/inference/tree/models.py
Labels: bug

#126 change elasticnetcv to logisticregressioncv
  causalml/propensity.py
Labels: enhancement

#129 Fix TravisCI FOSSA stage fail for PRs from forked repos
  .travis.yml
Labels: warning

#131 fix uplift curve with normalization when ATE is negative
  causalml/metrics/visualize.py
Labels: bug
