Repository uber/causalml, pull requests merged in 2022-02, with the labels that each got.

#468 Switching the joblib backend for UpliftRandomForestClassifier to threading
  causalml/inference/tree/uplift.pyx
Labels: bug

#476 Merely define preferred backend for joblib instead of hard-coding it
  causalml/inference/tree/uplift.pyx
  tests/test_uplift_trees.py
Labels: enhancement

#478 add missing trailing backtick
  docs/validation.rst
Labels: documentation

#474 Reformat code using black
  .github/workflows/black.yml
  CONTRIBUTING.md
  causalml/__init__.py
  causalml/dataset/classification.py
  causalml/dataset/regression.py
  causalml/dataset/synthetic.py
  causalml/feature_selection/__init__.py
  causalml/feature_selection/filters.py
  causalml/features.py
  causalml/inference/iv/drivlearner.py
  causalml/inference/iv/iv_regression.py
  causalml/inference/meta/__init__.py
  causalml/inference/meta/base.py
  causalml/inference/meta/drlearner.py
  causalml/inference/meta/explainer.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/tmle.py
  causalml/inference/meta/utils.py
  causalml/inference/meta/xlearner.py
  causalml/inference/nn/cevae.py
  causalml/inference/tf/dragonnet.py
  causalml/inference/tf/utils.py
  causalml/inference/tree/__init__.py
  causalml/inference/tree/plot.py
  causalml/inference/tree/utils.py
  causalml/match.py
  causalml/metrics/__init__.py
  causalml/metrics/classification.py
  causalml/metrics/const.py
  causalml/metrics/regression.py
  causalml/metrics/sensitivity.py
  causalml/metrics/visualize.py
  causalml/optimize/unit_selection.py
  causalml/optimize/utils.py
  causalml/optimize/value_optimization.py
  causalml/propensity.py
  docs/conf.py
  setup.py
  tests/conftest.py
  tests/const.py
  tests/test_cevae.py
  tests/test_counterfactual_unit_selection.py
  tests/test_datasets.py
  tests/test_features.py
  tests/test_ivlearner.py
  tests/test_match.py
  tests/test_meta_learners.py
  tests/test_propensity.py
  tests/test_sensitivity.py
  tests/test_uplift_trees.py
  tests/test_value_optimization.py
Labels: refactoring
