Repository uber/causalml, pull requests merged in 2023-10, with the labels that each got.

#681 Remove the numpy and pandas version restriction in pyproject.toml
  causalml/propensity.py
  pyproject.toml
Labels: dependencies

#688 Add governance documents
  ANTITRUST.md
  CHARTER.md
  GOVERNANCE.md
  MAINTAINERS.md
  STEERING-COMMITTEE.md
  TRADEMARKS.md
Labels: documentation

#691 Update GOVERNANCE.md
  GOVERNANCE.md
Labels: documentation

#686 Reduce sklearn dependency in causalml
  CONTRIBUTING.md
  Makefile
  causalml/inference/tree/_tree/__init__.py
  causalml/inference/tree/_tree/_classes.py
  causalml/inference/tree/_tree/_criterion.pxd
  causalml/inference/tree/_tree/_criterion.pyx
  causalml/inference/tree/_tree/_splitter.pxd
  causalml/inference/tree/_tree/_splitter.pyx
  causalml/inference/tree/_tree/_tree.pxd
  causalml/inference/tree/_tree/_tree.pyx
  causalml/inference/tree/_tree/_utils.pxd
  causalml/inference/tree/_tree/_utils.pyx
  causalml/inference/tree/causal/__init__.py
  causalml/inference/tree/causal/_builder.pxd
  causalml/inference/tree/causal/_builder.pyx
  causalml/inference/tree/causal/_criterion.pxd
  causalml/inference/tree/causal/_criterion.pyx
  causalml/inference/tree/causal/_tree.py
  causalml/inference/tree/causal/causalforest.py
  causalml/inference/tree/causal/causaltree.py
  pyproject.toml
  setup.py
Labels: dependencies

#696 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: documentation

#695 Modified to speed up UpliftTreeClassifier.growDecisionTreeFrom.
  causalml/inference/tree/uplift.pyx
Labels: enhancement
