Repository uber/causalml, pull requests merged in 2023-07, with the labels that each got.

#631 Fix AttributeError in builds with numpy>=1.24 and pandas>=2.0
  causalml/features.py
  causalml/metrics/sensitivity.py
  tests/test_counterfactual_unit_selection.py
Labels: bug

#632 Up the version to 0.14
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
Labels: documentation

#633 Update the python-publish workflow file to fix the package publish Gi…
  .github/workflows/python-publish.yml
Labels: bug

#641 Fix for builds on Mac M1 infrastructure
  causalml/inference/tree/causal/_builder.pyx
  envs/environment-py37.yml
  envs/environment-py38.yml
  envs/environment-py39.yml
Labels: installation

#634 code cleanups
  causalml/inference/iv/iv_regression.py
  causalml/inference/meta/base.py
  causalml/inference/meta/drlearner.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/tmle.py
  causalml/match.py
Labels: refactoring
