Repository uber/causalml, pull requests merged in 2024-04, with the labels that each got.

#758 757: add return_ci=True in sensitivity
  causalml/metrics/sensitivity.py
Labels: bug

#759 Update sensitivity tests with more meta-learners
  causalml/dataset/classification.py
  causalml/dataset/synthetic.py
  causalml/feature_selection/filters.py
  causalml/inference/iv/drivlearner.py
  causalml/inference/iv/iv_regression.py
  causalml/inference/meta/drlearner.py
  causalml/inference/meta/explainer.py
  causalml/inference/meta/rlearner.py
  causalml/inference/meta/slearner.py
  causalml/inference/meta/tlearner.py
  causalml/inference/meta/tmle.py
  causalml/inference/meta/xlearner.py
  causalml/inference/tree/causal/causaltree.py
  causalml/inference/tree/plot.py
  causalml/inference/tree/utils.py
  causalml/match.py
  causalml/metrics/sensitivity.py
  causalml/optimize/pns.py
  causalml/optimize/policylearner.py
  causalml/optimize/unit_selection.py
  causalml/optimize/value_optimization.py
  tests/test_sensitivity.py
  tox.ini
Labels: test

#761 fix typo in MAINTAINERS.md
  MAINTAINERS.md
Labels: documentation

#762 Update python-publish GHA to build multi-platform wheels
  .github/workflows/python-publish.yml
  .gitignore
  pyproject.toml
Labels: installation

#765 Remove musllinux build
  docs/conf.py
  pyproject.toml
Labels: installation
