Repository uber/causalml, pull requests merged in 2025-05, with the labels that each got.

#830 v0.15.4 release
  .gitignore
  README.md
  pyproject.toml
Labels: release

#831 fix runtime dependencies
  pyproject.toml
Labels: build

#832 Fix build errors
  .github/workflows/python-test.yaml
  .github/workflows/test-build-from-source.yml
  .github/workflows/test-conda-forge-install.yml
  .github/workflows/test-pypi-install.yml
  docs/installation.rst
  pyproject.toml
  setup.py
Labels: build

#834 install via `uv`
  docs/installation.rst
Labels: documentation
